// packages/toolbox/src/components/titlebar.vue
<script setup lang="ts">
import { getCurrentWindow } from '@tauri-apps/api/window'
import { Minus, Square, X } from 'lucide-vue-next'

const appWindow = getCurrentWindow()

async function minimize() {
  await appWindow.minimize()
}

async function toggleMaximize() {
  await appWindow.toggleMaximize()
}

async function close() {
  await appWindow.close()
}
</script>

<template>
  <div
    data-tauri-drag-region
    class="flex items-center h-10 bg-card border-b px-4 select-none"
  >
    <div data-tauri-drag-region class="flex-1 text-sm font-medium">
      工具箱
    </div>
    <div class="flex items-center gap-1">
      <button
        class="p-1.5 rounded hover:bg-muted transition-colors"
        @click="minimize"
      >
        <Minus class="size-4" />
      </button>
      <button
        class="p-1.5 rounded hover:bg-muted transition-colors"
        @click="toggleMaximize"
      >
        <Square class="size-3.5" />
      </button>
      <button
        class="p-1.5 rounded hover:bg-destructive/10 hover:text-destructive transition-colors"
        @click="close"
      >
        <X class="size-4" />
      </button>
    </div>
  </div>
</template>

// packages/jacc/src/components/TitleBar.tsx
import { getCurrentWindow } from '@tauri-apps/api/window'
import { Minus, Square, X } from 'lucide-react'

export function TitleBar() {
  const appWindow = getCurrentWindow()

  return (
    <div className="h-8 flex items-center bg-sidebar border-b border-border select-none">
      <div className="pl-3 text-xs text-muted" data-tauri-drag-region>
        jacc
      </div>
      <div data-tauri-drag-region className="flex-1 h-full" />
      <div className="flex h-full">
        <button
          onClick={() => appWindow.minimize()}
          className="w-11 h-full flex items-center justify-center hover:bg-border/50 text-muted-foreground"
        >
          <Minus size={14} />
        </button>
        <button
          onClick={() => appWindow.toggleMaximize()}
          className="w-11 h-full flex items-center justify-center hover:bg-border/50 text-muted-foreground"
        >
          <Square size={12} />
        </button>
        <button
          onClick={() => appWindow.close()}
          className="w-11 h-full flex items-center justify-center hover:bg-danger/80 hover:text-white text-muted-foreground"
        >
          <X size={14} />
        </button>
      </div>
    </div>
  )
}
